### PR TITLE
Files rename and missing contents added

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by jasongroce** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/patterns-practices, working directory: W:\xftt-s, target branch: master, target branch commit: 26f0d7da02366a289cce6cd767eeded617afb599, source branch: 9c8de949203dfebb9159a956b934ddf0/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbdf6b3e0-6d73-8157-ba4e-ca923d725704%5CPullRequest%5C201705172151082405-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasongroce** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/patterns-practices, working directory: W:\tjk3-s, target branch: master, target branch commit: 26f0d7da02366a289cce6cd767eeded617afb599, source branch: 9c8de949203dfebb9159a956b934ddf0/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbdf6b3e0-6d73-8157-ba4e-ca923d725704%5CPullRequest%5C201705172210010295-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasongroce** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/patterns-practices, working directory: W:\zlz1-s, target branch: master, target branch commit: 26f0d7da02366a289cce6cd767eeded617afb599, source branch: 9c8de949203dfebb9159a956b934ddf0/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbdf6b3e0-6d73-8157-ba4e-ca923d725704%5CPullRequest%5C201705172210185360-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasongroce** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/patterns-practices, working directory: W:\wkp1-s, target branch: master, target branch commit: 26f0d7da02366a289cce6cd767eeded617afb599, source branch: 9c8de949203dfebb9159a956b934ddf0/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbdf6b3e0-6d73-8157-ba4e-ca923d725704%5CPullRequest%5C201705172236119868-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasongroce** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/patterns-practices, working directory: W:\qf1s-s, target branch: master, target branch commit: 26f0d7da02366a289cce6cd767eeded617afb599, source branch: 9c8de949203dfebb9159a956b934ddf0/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbdf6b3e0-6d73-8157-ba4e-ca923d725704%5CPullRequest%5C201705172311111116-40%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-hearya** [comment]
Closing the request as the files has conflict. will create in PR with the updates.

**Pull request closed without merging**
